Update check_credentials.yml

diff --git a/.github/workflows/check_credentials.yml b/.github/workflows/check_credentials.yml
--- a/.github/workflows/check_credentials.yml
+++ b/.github/workflows/check_credentials.yml
@@ -60,3 +60,24 @@ jobs:
             echo "❌ Credentials couldn't be returned."
             exit 1
           fi
+          
+      - name: Set Git Credentials in Power BI Workspace
+        run: |
+          echo "🔐 Setting Git credentials..."
+      
+          payload=$(jq -n --arg token "${{ secrets.PAT }}" '{Provider: "GitHub", accessToken: {{ secrets.PAT }}}')
+      
+          response=$(curl -s -w "%{http_code}" -o patch_response.json -X PATCH \
+            "https://api.fabric.microsoft.com/v1/workspaces/${{ secrets.PBI_WORKSPACE_ID }}/git/myGitCredentials" \
+            -H "Authorization: Bearer $ACCESS_TOKEN" \
+            -H "Content-Type: application/json" \
+            -d "$payload")
+      
+          echo "Status Code: $response"
+          echo "Response:"
+          cat patch_response.json
+      
+          if [[ "$response" != "200" ]]; then
+            echo "🚨 Failed to set Git Credentials!"
+            exit 1
+          fi
