Update check_credentials.yml

diff --git a/.github/workflows/check_credentials.yml b/.github/workflows/check_credentials.yml
--- a/.github/workflows/check_credentials.yml
+++ b/.github/workflows/check_credentials.yml
@@ -42,3 +42,21 @@ jobs:
             echo "❌ Git connection not found or workspace is not a Fabric workspace."
             exit 1
           fi
+     
+      - name: Get my credentials
+        run: |
+          echo "🔍 Checking Git integration in Fabric workspace..."
+      
+          response=$(curl -s -w "%{http_code}" -o response.json \
+            -X GET "https://api.fabric.microsoft.com/v1/workspaces/${{ secrets.PBI_WORKSPACE_ID }}/git/myGitCredentials" \
+            -H "Authorization: Bearer $ACCESS_TOKEN" \
+            -H "Content-Type: application/json")
+      
+          echo "Status Code: $response"
+          echo "Response Body:"
+          cat response.json | jq
+      
+          if [[ "$response" != "200" ]]; then
+            echo "❌ Credentials couldn't be returned."
+            exit 1
+          fi
